* architecture
** level
*** room
**** tile
     the floor, wall
**** player
     hp, exp, str, equipment, pack, gold, pack
**** monster
     name, exp, damage, type
**** door
     normal/secret
**** stair
     up/down
**** trap
     be careful
**** things
***** gold
      pick up
***** scrolls
      read
***** potion
      quaff
***** ring
      equip
***** weapon
      equip, fight
***** armor
      equip, protect
***** wand
      equip, fight
***** food
      eat, recover from starve
*** passage
** UI
*** info
*** title
*** story
*** rip
*** win

* translate
** 背景交代
   你刚刚从当地的战士公会毕业。经历了许多酸甜苦辣，你完成了训练，准备
   去展开一场危险的冒险。作为对你所学的测试，公会会长要求你去末日地下
   城。你的任务是拿回【炎多的护身符】。完成这项任务，你将成为公会正式
   的一员。另外，你可以保留从地下城拿到的所有财宝。

   为了你的旅程，会长给了你一把附了魔的狼牙棒，一把弓，和一袋从黑山的
   龙处拿来的箭。你还得到了精灵制作的铠甲以及足够到达地下城入口的粮食。
   你向亲人和朋友们告别，这可能是最后的告别，接着你踏上了旅途。

   经过几天平静的旅程，你看到了古代遗迹的地下城入口。天色已晚，你在入
   口处露营，进入梦乡。新的早晨，你拿上武器，穿上铠甲，吃完剩下的食物，
   进入了地下城。

* log
** 04.01
   首要问题是生成地图，先导入两张图片，地板和墙，制作成tileset，给
   tilemap来用，接着就需要使用autoload全局的script来控制map的生成。
** 04.12
   整个游戏的逻辑都是基于网格，碰撞系统可以直接用网格模拟。在 project
   setting 里添加新的按键，对角线移动简单地实现。
** 04.14
   之前都在摸鱼，今天才算是真正在做，autoload一个生成地图的script，房
   间用一个矩形表示，不断地生成随机大小的房间，房间不能太小，至少是要
   3x3,因为人物就要占一格，但我觉得还是狭窄了点，限制成最最小4x4,有一
   个最大尝试次数，每生成一个房间就要和已生成的所有房间进行比较，看有
   没有相交（rect2这种数据结构提供了intersect方法），没相交才加入，本
   来还担心如果次数太少会不会导致生成的房间少，太多会不会影响性能，最
   后发现次数只要超过一个很小的最小值，之后增加多少次生成结果也是差不
   多，生成房间的数量直觉上来说收敛于地图大小和房间大小的关系，最后我
   也就限制了10次，这样可以保证不会生成超过10个房间，不然游戏会变得困
   难并且更耗时间，10次下来基本上可以生成大概率生成3-5个房间，类似正态
   分布曲线。路的生成就是简单的L型路径，不处理覆盖的问题，却生成了有趣
   的路径，找到两房间随机的两个点，从左边一点往右走，再往上或者下走，
   随机决定是先水平再垂直还是先垂直再水平。前一个房间到后一个房间保证
   有一条路，就生成了流通图。

   这种生成方法简单，但是不太完美，有时候会导致房间的一面墙被洗掉，不
   过无伤大雅。地图生成后玩家可以看到整副地图，这和原版的rogue是不一致
   的。我先把地图数据获取到，然后只set_cell玩家所在的就九宫格，就达到
   了探索地图的效果。
** 04.17
   又摸鱼两天，今天发现截止日期是5月19日，这是答辨日期的最后，5月15号
   是第二次论文检查日期。5月10号这游戏差不多就要做好，才发现时间紧迫。
   今天把怪物加了进去，找对应图片找了一两小时，最后还是有4种怪物是找不
   到对应的，只好用相似的先代替，先把游戏做好再说。又把卷轴，药水，法
   杖，武器，护甲，金币，食物，戒指加了进去，机械重复劳动，比较无聊的
   过程。这套美术能用的东西非常多，省了很多事。

   物品，怪物，人物这些都弄好后，就想放到地图上看看效果，想把人物里面
   的几个函数作为公用函数，物品怪物人物都可以是一种对象，这个游戏就只
   有地图和对象两种东西，但是弄了一个新scene把物乖人都instance进去，再
   把人物的代码移动过去，然后extend之，却总是不成功，弄了很长时间，感
   觉对于godot的这些继承，调用的关系还是没怎么搞清楚，今天很累了，就先
   到此为止。
** 04.18
   今天对继承的关系弄的比较清楚了，可以spawn出各种想要的东西了，基本上
   一个node出来是要使用他自己attach的script，如果没有script，就会使用
   这个node本身提供的方法，由于设置地图位置都是需要tilemap的方法才行，
   所以先是写一个大家共同使用的script，然后把所有的怪物道具包括玩家都
   attach到这个script上，这样一来想spawn就spawn。可是觉得这样不够优雅，
   为什么子node就不能直接inherit父node的script，不需要每个都去attach就
   好了，虽然可以全选来操作。不过以后每种怪物道具都是要单独写一个
   script的，所以也无伤大雅，但是除了特殊效果的道具，其他的元素都比较
   相似，怪物方面我想是不是能直接在inspector里设置护甲，攻击力这些，而
   不用自己写一个script出来，但是不export就不能在inspector里设置。应该
   是有去除这种冗余的方法的，只是我不知道。

   怪物也生成出来了，通过延迟加载的方法，使得怪物和地图可以模拟一个视
   野的效果，突然想出“没有被观察到就不存在”。在这个游戏里确实是如果人
   物没有观察到，它就是不存在的（没有分配内存）。再玩家按一个键后，先
   时把玩家接下来要看到的生成好，玩家才移动到格子上，相当于暂停了玩家
   的时间。目前还没有怪物追杀主角的算法，有可能是要实现a星这样的算法，
   不过看rogue的源代码，似乎没有说要用到什么人工智能算法，时间有限，如
   果去复习人工智能，一天就要过去了。
** 04.20
   昨天摸鱼，今天继续做，做界面，觉得这是比较紧要的事情，因为演示不可
   能演示到通关，所以开局效果要好。看了一下教程，界面是比较容易做的，
   基本上几个container给划分，用一个viewport来显示下城，下面显示状态，
   右边显示背包，背包在原版游戏里是不直接显示的，需要通过文字交互，如
   果我也用文字来做，我觉得还没有直接做一个背包容易，而且背包更加直观。
   godot的ui系统和html有点像的，所有的界面系统可能都差不多吧，这不是一
   个什么能创新的地方。一开始加进取调大小总是会变化。size flags的
   expand打开是很关键的，不然东西都会挤在一起，失去了vectical\horizonl
   本身的作用。

   把状态信息也加上了，目前只是一个label，没有什么数据交换的地方，换了
   一个地板的图片，背景设置成全黑，比较成样子了。

   把玩家的移动进行了抽象，抽象成走一格，然后基于它写一个贪心走路法，
   由于调用的是走一步的函数，所以可以把地图划出画出来，如果不调用，直
   接到了终点，中间的路就还是黑的。

   对generator进行了重构，计划是有一个二维数组来存储地图所有的信息，原
   来只是存了tile的id，enum了几个变量表示怪物玩家道具楼梯地板墙。
** 04.21
   今天半摸鱼，半开发。实现了到下一层去，其实就是重新加载scene，然后把
   之前的信息存到autoloads里。
** 04.23
   昨天摸鱼，今天也是，晚上写了一点，写了一个怪物的追踪，bug非常多，改
   了挺久，最后似乎是没问题了，追踪算法不是什么a星，甚至都不是广义\深
   度优先搜索，只是很简单的判断玩家和怪物的相对位置，然后向那个方向移
   动，这就导致了有时候不会动，不过这种笨的智能却伪装出了高等的智能。
   被signal卡了很久，自定义了一个signal，人物移动就会发送，要等怪物出
   来了再连接signal，不然没怪的时候也会判断，不停崩溃。这个游戏基本上
   跟着主角的时间走。所以这个signal可以充当计时器。
** 04.24
   今天也是半摸鱼，结果做到瓶颈了，战斗部分难做，把数据结构进行了修改，
   是为了方便获取怪物的node（根据所在位置），用了一个inner class，真的
   难用，然后就各种各样的base错误。今天产生了绝望的感觉。debug很难，有
   时候可以，有时不行。

   睡觉前还是找到问题所在的，改了之后稳定运行，只是战斗和碰撞还有点小
   问题，这个同步总有不完善的地方。
** 04.26
   今天做ui部分，状态栏用label，发几个signal出来，收到就改一下label的
   text属性，一开始改完发现没用，发现要把原来设置的text去掉才有用，可
   能insepector里的text会覆盖吧。然后做了一个开始游戏的界面，从网上找
   了一张背景图放到textureRect上，然后整3个按钮出来。定义一下_pressed()方
   法就能实现点击发生什么了，inspector里的hover color也是点点鼠标就能
   设置了。结果发现load再instance并不能开始游戏，网上查是要add_child，
   结果add完和原来的scene搞在一起，显示异常，而且因为add_child之后root
   变了，之前hardcode的部分崩了。再上网查，其实是要get_tree()后再
   change_scene()来切换scene，退出只要调用quit()就好了。

   接下来就对怪物的战斗debug，弄了半天，一直以为是update_pos导致数据不
   一致产生的bug，后来发现如果我不战斗就没问题，所以应该是战斗部分。怪
   物死了之后我是set_visible(false)让它看不见，然后把地图数据设置成地
   板，可是这样之后我发现，尽管我看不见它，但它并没有消失，导致我没法
   移动到它死掉的地方，之所以这么做，是考虑到如果把这个node删除了，可
   能需要维护新的index，比较麻烦，结果也不行，之后我就queue_free，本来
   以为这样index就会出问题，却不会，因为它要等到可以“安全”删除node之后
   才删除，所以我也就不需要维护index。

   晚上发现还是要维护index的，一开始我想是在进入下一个场景再free，但是
   这样做怪物不会从地图上消失，call_deffered也和queue_free效果差不多，
   最后我在怪物死的时候立刻free，然后发送一个signal，所有怪物立刻更新
   自己的index。然后又给加了一个过场动画，非常简单，一段之前自己翻译的
   文字贴上去，再加一个继续的按钮。又加了bgm，使用beyond的dead romance，
   用一个autoloads的scene来播放，这样到下一层的时候音乐不会重新播放。
   但是这个音乐我自己听过很多次，之前已经进行了相像，而且也知道是为了
   探索林过云而作的曲子，黑案诡异的氛围和这个游戏还是比较搭配的，只是
   我自己听得多所以不能进入游戏的临场感。不过只有一首bgm觉得有点单调，
   还考虑要不要干脆去掉，完全不用音乐，不管那么多，暂且先这样。又设置
   了一下人物和怪物的z index，能让他们显示在物品的上面，原来是会被挡住
   的，因为godot根据node的顺序绝对先画谁，玩家总是第一个node，所以会被
   挡在下面。
** 04.27
   今天早上做了一点，之后摸鱼。从hatari版的rogue里偷了一个rip图片出来，
   然后又把beyong的last man who known you转成ogg作为背景音乐，加了退出
   和新生两个按钮，直接attach到start scene的两个脚本。然后给怪物export
   一个字符串出来做为怪物的名字，xeroc实在不会翻译，就没翻译，网上查这
   个好像是一种半人大象的首领。也不是英语单词，谷歌翻译也识别不到。
** 04.28
   几乎摸鱼一整天，晚上写了一个怪物的战斗部分，发signal却发现比较难获
   得到怪物的node。最后直接调用函数，不使用signal。signal应该来说是一
   个对象发送之后多个对象响应比较有用，如果只是用来调UI显示的东西就有
   点杀鸡用牛刀。
** 04.29
   今天做了一个背包，导入slot的图片，做成tilemap，但是tilemap做为一个
   control的儿子却不跟着父亲的动，这里面的位置设置还是有点不能理解，先
   不管那么多，做出基本功能。首先是弄了一个单独的thing脚本，extend了
   objects.gd，get到inventory里slot的node。给玩家添加一个捡东西的按键，
   然后发送一个signal，所有的物品处理他，判断自己是不是在玩家的脚下，
   是的话就调用slot.gd里的add_item。先是duplicate，然后add_child，再
   set_position，再把原来的node给free了。tilemap必须要add_child，才能
   给儿子设置位置。

   然后出来一个问题，进到下一层的时候，由于scene重新加载了，所以背包里
   的东西又是空的，一开始是想能不能只重新加载子scene，但是没找到方法，
   无奈就用autoload全局存储。一个2维数组，要么是空，要么是things里node
   的index，这样开新的scene之后就能根据index再加进来。但是有一个问题，
   物品刚出来的时候有可能会重名，于是godot就会自动给名字后面加入数字，
   比如gold，gold2,这样一来就无法得到scene里正确的index，因为做为数据
   库的scene都没有带数字的node，于是去查string有什么方法可以用，似乎没
   有什么直接去除字符串尾部数字的方法，就自己写实现了一个很无脑的，把
   数字全部replace成空。因为gdsciprt还是比较高级的语言，写底层不好写，
   本来应该iterate这个字符串，找到第一个数字就返回位置，然后把这后面的
   都去掉，或者用substr取前面，但是这里面不知道怎么表示字符的字面量，
   先不管这个了，就用很蠢的replace方法。

   结果发现光是替换数字是没用的，因为还会给你加@，一开始还以为是
   replace本身有什么问题，换种方法写，最后才发现就是会给你加@，也不知
   道多了以后会不会加别的东西。

   今天最后的时间完成了spawn_thing，因为多级结构，导致原来的函数不能用
   了，food和gold是没有子node的，因为没有多种food和多种gold，而weapon，
   armor等是有子node的，因为有不同的武器和铠甲。原来是保存things里子
   node的index在autoload里，这样换图的时候再根据这个index重新放到物品
   栏里，现在这个index是父node了，这样就不行。查文档发现一个find_node
   的函数，可以递归搜索，这样一来我只要递归搜索things就能找到对应的
   node了。于是从保存index变成了保存node.name，效果很好。

   对godot还是缺乏经验，但经过这段时间，我发现这个东西的逻辑是这样：
   node组成scene，scene可以instance成别的scene的儿子，实际上scene就是
   node，不过scene可以保存到硬盘上来载入，而script是控制这个node的行为，
   signal可以在node间传递信息，autoload是全局，信息也可以通过autoloads
   传递，control型的node用来做界面，其他node实现游戏内容，node之间有继
   承关系，查文档可以查到他新有的方法和属性，要知道所有的方法和属性要
   往上查。这套描述世界的模形还是比较直观优雅的。只是gdscript的通用工
   具有点缺乏。
** 05.04
   很惭愧，忙别的事情快一周。今天先是要做一个鼠标在道具栏滑动时的效果，
   先添加两个图片，一个是hover时的效果，一个是选中，做成control的子
   sprite，和tilemap同级别。先给隐藏起来，然后连接control的信号，有两
   个用的到，一个是gui_input，一个是mouse_exit。给gui_input的event参数
   做判断，motion的时候就是不断地获取map上的位置，然后把sprite set到这
   个位置，mouse_exit的时候隐藏，两个sprite都是这样，非常容易就实现了。
   我希望通过selected的时候显示物品的信息。selected的时候发送一个信号，
   label node接收到后，可以查全局item上的名字，然后就能根据名字
   find_node，接着再得到物品说明的文字。接下来就是export出说明，然后来
   输入就好。全部都先attach一格things.gd，export了item_name，全选就能
   统一赋值，暂且只有武器和护甲有详细说明，其他都是某种xx糊弄过去。然
   后我觉得生成地图的算法还是不太好，会出现两个房间紧挨着的情况，就写
   了一个判断太近的函数加进去，效果还不错。不过我感觉还是没有rogue原版
   游戏的地图漂亮。本来应该直接把rogue的算法抄过来。但是那个源码命名的
   缩写总是看不太懂，然后数据结构又错综复杂，关联性很强，总之感觉这代
   码并不是很好，很难读（可能是自己菜吧）。暂且就先这样，等有空余时间
   再研究透彻。

   然后又给加了消息，目前就只有战斗会有信息，也只是很简陋的实现，用
   signal，玩家方面容易，怪物就不行了，因为每个怪物都进行连接也不好，
   最后直接get_node消息label，调用里面的函数就完事了，像这种一个目标与
   另一个目标通信，用不到signal，也不好用，signal应该用在一个或者多个
   目标与多个目标通信。也就是给text赋值，就自动更新了。

   给金币单独划分开来，因为捡金币就是直接增加数值，不会丢到背包里。然
   后又做了一个背包满格的判定，这个也很简单，只是原来的代码不够优雅，
   所以增加的代码也不优雅，这个游戏代码需要重构。

   最后做了一个丢东西的，问题就来了，我保存在全局里的只有原名字，没有
   add_child之后的名字，这样我就get不到了，一开始小机灵鬼的用index来
   get，就是6*x+y这样，但很快就发现不行，因为丢掉中间的child之后，
   index最大值就减少了，就无效了，然后我又写了一个offset函数来计算少了
   多少个，但仍然有问题，因为丢下再捡起来于node tree是加到末尾，而在背
   包中是加到第一个空位上，无奈只能用性能比较差的方法，就是把所有的
   child检查，看位置匹配不匹配，就是遍历来得到node，仔细一想，似乎也没
   多少性能影响，因为物品就很少。
** 05.05
   今天一上来就发现过图之后，就丢不了东西了，会出错，原因在于找不到
   tilemap的方法，因为objects才有这种方法，之前是直接extend他，
   duplicate的时候会是一模一样的，也就是script还是objects的script，而
   不是things的script，就是一个转换的问题，捡起来的时候要从objects转成
   things，丢掉又要转回objects，觉得这种实现比较糟糕吧，先修好bug，以
   后再重构。然后就是不知道为什么，可能以前手滑了把level放到了
   autoloads这个目录下，而project setting没有autoloads它，显然是意外放
   进去的，直接拖出来，似乎godot自动重构路径，没发生什么问题。
** 05.06
   今天先改了一下人物的操作方法，本来的话按住一个朝某方向移动的键，是
   不会一直移动的，因为用的是is_action_pressed()，只有按下会触发，这样
   就很不方便操作，要不停的按才能走路，虽然有贪心移动的键，但那个太贪
   了，一下子甚至走到分辨率外了，看不到中间的路。is_action()又会按一下
   走两格，虽然按住会一直走。上网查了发现要用Input，原来用的是event。
   我也不知道是为什么，可能是两种不同的机制吧。实现了之后就比较舒服，
   方便测试。然后又觉得消息栏的消息不会清空也不太好，有种出了bug的感觉，
   就加了一个timer，非常容易，timeout了就清空，有消息出来才开始计时。

   接着就做了一个穿装备的功能，穿上就被背景换成绿色，目前也只有铠甲有
   作用，武器也可以装备，但是没有实际效果，武器是加攻击，但我们人物的
   属性里其实没有攻击力，攻击力要摇筛子，武器增加最大值，这个以后再加。
   然后又把spawn护身符加进去。最近觉得做起来越来越简单了，但是因此变懒
   了。就目前这个样子毕业不成问题了，代码虽然才700行，但是拿个60分是肯
   定可以的，而且很可能80分都有，因为这个游戏看起来很强，老师也不会细
   看，演示效果好。

   又做了一个换装的功能，原来是可以穿很多件衣服，现在只能穿一件，在
   autoloads里定义变量记录装备的位置，换地图的时候也可以从这里load进来，
   就不会因为换图又变得像没穿一样。
